src/Api/Controllers/AnimalController.cs
using Domain.Entities;
using Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Api.Controllers
{
  public class AnimalController : Controller
  {
    private readonly IAnimalRepository _animalRepository;
    public AnimalController(IAnimalRepository animalRepository)
    {
      _animalRepository = animalRepository;
    }

    public async Task<IActionResult> Index()
    {
      return View(await _animalRepository.ReadAll());
    }
    public IActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Animal animal)
    {
      try
      {
        if (!ModelState.IsValid)
        {
          await _animalRepository.Create(animal);
          TempData["Sucesso"] = "Salvo com sucesso!";
          return RedirectToAction("Index");
        }
        return View(animal);
      }
      catch (System.Exception)
      {
        TempData["Erro"] = "Falha ao salvar!";
        return RedirectToAction("Index");
      }
    }

    public async Task<IActionResult> Update(int id)
    {
      var animal = await _animalRepository.Read(id);
      return View(animal);
    }

    [HttpPost]
    public async Task<IActionResult> Update(Animal animal)
    {
      try
      {
        if (!ModelState.IsValid)
        {
          await _animalRepository.Update(animal);
          TempData["Sucesso"] = "Salvo com sucesso!";
          return RedirectToAction("Index");
        }
        return View(animal);
      }
      catch (System.Exception)
      {
        TempData["Erro"] = "Falha ao salvar!";
        return RedirectToAction("Index");
      }
    }

    public async Task<IActionResult> Delete(int id)
    {
      Animal animal = await _animalRepository.Read(id);
      return View(animal);
    }

    public async Task<IActionResult> ConfirmDelete(int id)
    {
      await _animalRepository.Delete(id);
      return RedirectToAction("Index");
    }
  }
}

src/Api/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Domain.Entities;

namespace Api.Controllers
{
  public class HomeController : Controller
  {
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
      _logger = logger;
    }

    public IActionResult Index()
    {
      return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
      return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
  }
}

src/Api/Controllers/TreatmentController.cs
using Domain.Entities;
using Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Api.Controllers
{
  public class TreatmentController : Controller
  {
    private readonly ITreatmentRepository _treatmentRepository;
    public TreatmentController(ITreatmentRepository treatmentRepository)
    {
      _treatmentRepository = treatmentRepository;
    }
    public async Task<IActionResult> Index()
    {
      return View(await _treatmentRepository.ReadAll());
    }
    public IActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public async Task<IActionResult> Create(Treatment treatment)
    {
      try
      {
        if (!ModelState.IsValid)
        {
          await _treatmentRepository.Create(treatment);
          return RedirectToAction("Index");
        }
        return View(treatment);
      }
      catch (System.Exception)
      {
        TempData["Erro"] = "Falha ao salvar!";
        return RedirectToAction("Index");
      }
    }

    public async Task<IActionResult> Update(int id)
    {
      var treatment = await _treatmentRepository.Read(id);
      return View(treatment);
    }

    [HttpPost]
    public async Task<IActionResult> Update(Treatment treatment)
    {
      try
      {
        if (!ModelState.IsValid)
        {
          await _treatmentRepository.Update(treatment);
          TempData["Sucesso"] = "Salvo com sucesso!";
          return RedirectToAction("Index");
        }
        return View(treatment);
      }
      catch (System.Exception)
      {
        TempData["Erro"] = "Falha ao salvar!";
        return RedirectToAction("Index");
      }
    }
    public async Task<IActionResult> Delete(int id)
    {
      Treatment treatment = await _treatmentRepository.Read(id);
      return View(treatment);
    }

    public async Task<IActionResult> ConfirmDelete(int id)
    {
      await _treatmentRepository.Delete(id);
      return RedirectToAction("Index");
    }
  }
}

src/Api/Controllers/VeterinaryController.cs
using Domain.Entities;
using Domain.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Api.Controllers
{
  public class VeterinaryController : Controller
  {
    private readonly IVeterinaryRepository _veterinaryRepository;
    public VeterinaryController(IVeterinaryRepository veterinaryRepository)
    {
      _veterinaryRepository = veterinaryRepository;
    }

    public async Task<IActionResult> Index()
    {
      return View(await _veterinaryRepository.ReadAll());
    }
    public IActionResult Create()
    {
      return View();
    }
    [HttpPost]
    public async Task<IActionResult> Create(Veterinary veterinary)
    {
      try
      {
        if (!ModelState.IsValid)
        {
          await _veterinaryRepository.Create(veterinary);
          return RedirectToAction("Index");
        }

        return View(veterinary);
      }
      catch (System.Exception)
      {
        TempData["Erro"] = "Falha ao salvar!";
        return RedirectToAction("Index");
      }
    }

    public async Task<IActionResult> Update(int id)
    {
      var veterinary = await _veterinaryRepository.Read(id);
      return View(veterinary);
    }
    [HttpPost]
    public async Task<IActionResult> Update(Veterinary veterinary)
    {
      try
      {
        if (!ModelState.IsValid)
        {
          await _veterinaryRepository.Update(veterinary);
          TempData["Sucesso"] = "Salvo com sucesso!";
          return RedirectToAction("Index");
        }
        return View(veterinary);
      }
      catch (System.Exception)
      {
        TempData["Erro"] = "Falha ao salvar!";
        return RedirectToAction("Index");
      }
    }

    public async Task<IActionResult> Delete(int id)
    {
      Veterinary veterinary = await _veterinaryRepository.Read(id);
      return View(veterinary);
    }

    public async Task<IActionResult> ConfirmDelete(int id)
    {
      await _veterinaryRepository.Delete(id);
      return RedirectToAction("Index");
    }
  }
}

src/Api/Views/Animal/Create.cshtml
@model Domain.Entities.Animal
@{
    ViewData["Title"] = "Cadastro de animal";
}

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<div>
  <h3 class="display-2">Cadastro de animal</h3>
</div>
<br />

  <form class="col-md-6" asp-controller="Animal" asp-action="Create" method="post">
    <div class="form-group mb-2 ">
      <label for="name">Nome</label>
      <input type="text" asp-for="Name" class="form-control" placeholder="Nome do animal">
      @Html.ValidationMessageFor(x => x.Name)
    </div>
    <div class="form-group mb-2">
      <label for="breed">Raça</label>
      <input type="text" asp-for="Breed" class="form-control" placeholder="Raça do animal">
      @Html.ValidationMessageFor(x => x.Breed)
    </div>
    <div class="form-group mb-2">
      <label for="age">Idade</label>
      <input type="number" asp-for="Age" class="form-control" placeholder="Idade do animal em meses">
      @Html.ValidationMessageFor(x => x.Age)
    </div>
    <br />
    <div class="form-group col-md-6 mb-2">
      <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-ok"></i> Salvar</button>
      <a class="btn btn-danger" asp-action="Index" asp-controller="Animal" role="button"><i class="glyphicon glyphicon-remove"></i> Cancelar</a>
    </div>
</form>

src/Api/Views/Animal/Delete.cshtml
@{
    ViewData["Title"] = "Excluindo animal";
}


<div class="text-center">
    <h3>Tem certeza que deseja excluir o animal <b>(@Model.Name)?</b></h3>
<br />

    <div class="btn-group" role="group">
            <a role="button" class="btn btn-success me-2" asp-action="ConfirmDelete" asp-controller="Animal" asp-route-id="@Model.Id"><i class="glyphicon glyphicon-ok-circle"></i> Sim</a>
            <a role="button" class="btn btn-danger me-2" asp-action="Index" asp-controller="Animal"><i class="glyphicon glyphicon-remove-circle"></i> Não</a>
    </div>
</div>

src/Api/Views/Animal/Index.cshtml
@model List<Domain.Entities.Animal>
@{
    ViewData["Title"] = "Animal";
}

@if (TempData["Sucesso"] != null)
{
  <div class="alert alert-success" role="alert">
    <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
    @TempData["Sucesso"]
  </div>
}

@if (TempData["Erro"] != null)
{
  <div class="alert alert-danger" role="alert">
    <button type="button" class="btn btn-danger btn-sm close-alert" aria-label="Close">X</button>
    @TempData["Erro"]
</div>
}

<div className="main">
  <h2>Todos Animais</h2>
  <br />

<div class="">
  <a class="btn btn-primary" asp-controller="Animal" asp-action="Create"><i class="glyphicon glyphicon-plus"></i> Novo Animal</a>
</div>

<br />

  <table class="table table-borderless table-light" id="table">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Nome</th>
        <th scope="col">Raça</th>
        <th scope="col">Idade</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody>
      @if (Model != null && Model.Any())
              {
                  foreach (var animais in Model)
                  {
                      <tr>
                        <td>@Html.DisplayFor(modelItem => animais.Id)</td>
                        <td>@Html.DisplayFor(modelItem => animais.Name)</td>
                        <td>@Html.DisplayFor(modelItem => animais.Breed)</td>
                        <td>@Html.DisplayFor(modelItem => animais.Age) meses</td>
                        <td>
                            <div class="btn-group" role="group">
                              <a role="button" class="btn btn-primary" asp-route-id="@animais.Id" asp-controller="Animal" asp-action="Update"><i class="glyphicon glyphicon-pencil"></i> Editar</a>
                              <a role="button" class="btn btn-danger" asp-route-id="@animais.Id" asp-controller="Animal" asp-action="Delete"><i class="glyphicon glyphicon-trash"></i> Excluir</a>
                            </div>
                        </td>
                      </tr>
                  }
              }
          </tbody>
  </table>
</div>

src/Api/Views/Animal/Update.cshtml
@model Domain.Entities.Animal
@{
    ViewData["Title"] = "Editar";
}

<div>
  <h2 class="display-4">Editar</h2>
</div>
      <form asp-controller="Animal" asp-action="Update" method="post">
        <input type="hidden" asp-for="Id"></input>
        <div class="form-group">
            <label for="name">Nome</label>
            <input type="text" asp-for="Name" class="form-control" id="name">
            @Html.ValidationMessageFor(x => x.Name)
        </div>
        <div class="form-group">
            <label for="breed">Raça</label>
            <input type="text" asp-for="Breed" class="form-control" id="breed">
            @Html.ValidationMessageFor(x => x.Breed)
        </div>
        <div class="form-group">
            <label for="age">Idade</label>
            <input type="number" asp-for="Age" class="form-control" id="age">
            @Html.ValidationMessageFor(x => x.Age)
        </div>
        <br />
        <div class="form-group col-md-6">
          <button class="btn btn-success" role="button" type="submit"><i class="glyphicon glyphicon-ok"></i> Salvar</button>
          <a class="btn btn-danger" asp-action="Index" asp-controller="Animal" role="button"><i class="glyphicon glyphicon-remove"></i> Cancelar</a>
        </div>
      </form>

src/Api/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
<div class="text-center">
    <h1 class="display-4">Olá, tudo bem?</h1>
    <h2 class="displat-4">Seja bem vindo ao painel de atendimentos veterinários.</h2>
    <p>Um projeto ASP.NET Core MVC desenvolvido por <a href="https://www.linkedin.com/in/michel-claro/">Michel Claro</a>.</p>
</div>

src/Api/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VeterinaryClinic</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Veterinary.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.13.1/datatables.min.css" />
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Clínica Veterinária</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="Index">Animal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Treatment" asp-action="Index">Atendimentos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Veterinary" asp-action="Index">Veterinários</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="footer">
            &copy; 2022 - Veterinary Clinic - Michel Claro
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.13.1/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Api/Views/Treatment/Create.cshtml
@model Domain.Entities.Treatment
@{
    ViewData["Title"] = "Cadastro do atendimento";
}

<div>
  <h2 class="display-4">Cadastro de atendimento</h2>
</div>
<br />
  <form class="col-md-6 mb-2" asp-controller="Treatment" asp-action="Create" method="post">
    <div class="form-group mb-2">
      <label for="name">Observação</label>
      <input type="text" asp-for="Comment" class="form-control" placeholder="Observação">
      @Html.ValidationMessageFor(x => x.Comment)
    </div>
    <div class="form-group mb-2">
      <label for="breed">Animal</label>
      <input type="number" asp-for="AnimalId" class="form-control" placeholder="Id do animal">
      <span>Não sabe o ID do animal? Consulte aqui!</span>
      <a class="btn btn-primary mb-2 mt-2" asp-action="Index" asp-controller="Animal" role="button"><i class="glyphicon glyphicon-search"></i></a>
      @Html.ValidationMessageFor(x => x.AnimalId)
    </div>
    <div class="form-group mb-2">
      <label for="age">Veterinário</label>
      <input type="number" asp-for="VeterinaryId" class="form-control" placeholder="Id do veterinário">
      <span>Não sabe o ID do veterinário? Consulte aqui!</span>
      <a class="btn btn-primary mb-2 mt-2" asp-action="Index" asp-controller="Veterinary" role="button"><i class="glyphicon glyphicon-search"></i></a>
      @Html.ValidationMessageFor(x => x.VeterinaryId)
    </div>
    <br />
    <div class="form-group col-md-6 mb-2">
      <button class="btn btn-success" role="button" type="submit"><i class="glyphicon glyphicon-ok"></i> Salvar</button>
      <a class="btn btn-danger" asp-action="Index" asp-controller="Animal" role="button"><i class="glyphicon glyphicon-remove"></i> Cancelar</a>
    </div>
</form>

src/Api/Views/Treatment/Delete.cshtml
@{
    ViewData["Title"] = "Excluindo atendimento";
}

<div class="text-center">
    <h3>Tem certeza que deseja excluir o atendimento <b>(@Model.Id)?</b></h3>
<br />

    <div class="btn-group" role="group">
        <a role="button" class="btn btn-success me-2" asp-action="ConfirmDelete" asp-controller="Treatment" asp-route-id="@Model.Id"><i class="glyphicon glyphicon-ok-circle"></i> Sim</a>
        <a role="button" class="btn btn-danger me-2" asp-action="Index" asp-controller="Treatment"><i class="glyphicon glyphicon-remove-circle"></i> Não</a>
    </div>
</div>

src/Api/Views/Treatment/Index.cshtml
@model List<Domain.Entities.Treatment>
@{
    ViewData["Title"] = "Treatment";
}

<div className="main">
  <h2>Todos Atendimentos</h2>
  <br />

<div class="new">
    <a class="btn btn-primary" asp-controller="Treatment" asp-action="Create"><i class="glyphicon glyphicon-plus"></i> Novo Atendimento</a>
</div>

<br />

  <table class="table table-borderless table-light" id="table">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Observação</th>
        <th scope="col">Nome (Animal)</th>
        <th scope="col">Raça (Animal)</th>
        <th scope="col">Idade (Animal)</th>
        <th scope="col">Veterinário</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody>
      @if (Model != null && Model.Any())
              {
                  foreach (var treatments in Model)
                  {
                      <tr>
                        <td>@Html.DisplayFor(modelItem => treatments.Id)</td>
                        <td>@Html.DisplayFor(modelItem => treatments.Comment)</td>
                        <td>@Html.DisplayFor(modelItem => treatments.Animal.Name)</td>
                        <td>@Html.DisplayFor(modelItem => treatments.Animal.Breed)</td>
                        <td>@Html.DisplayFor(modelItem => treatments.Animal.Age)</td>
                        <td>@Html.DisplayFor(modelItem => treatments.Veterinary.Name)</td>
                        <td>
                            <div class="btn-group" role="group">
                              <a role="button" class="btn btn-primary" asp-route-id="@treatments.Id" asp-controller="Treatment" asp-action="Update"><i class="glyphicon glyphicon-pencil"></i> Editar</a>
                              <a role="button" class="btn btn-danger" asp-route-id="@treatments.Id" asp-controller="Treatment" asp-action="Delete"><i class="glyphicon glyphicon-trash"></i> Excluir</a>
                            </div>
                        </td>
                      </tr>
                  }
              }
          </tbody>
  </table>
</div>

src/Api/Views/Treatment/Update.cshtml
@model Domain.Entities.Treatment
@{
    ViewData["Title"] = "Editar";
}

<div>
  <h2 class="display-4">Editar</h2>
</div>
      <form asp-controller="Treatment" asp-action="Update" method="post">
        <input type="hidden" asp-for="Id"></input>
        <div class="form-group">
            <label for="name">Observação</label>
            <input type="text" asp-for="Comment" class="form-control" placeholder="Observação">
            @Html.ValidationMessageFor(x => x.Comment)
        </div>
        <div class="form-group">
            <label for="name_animal">Nome (Animal)</label>
            <input type="text" asp-for="Animal.Name" class="form-control" placeholder="Nome do animal">
            @Html.ValidationMessageFor(x => x.Animal.Name)
        </div>
        <div class="form-group">
            <label for="breed">Raça (Animal)</label>
            <input type="text" asp-for="Animal.Breed" class="form-control" placeholder="Raça do animal">
            @Html.ValidationMessageFor(x => x.Animal.Breed)
        </div>
        <div class="form-group">
            <label for="age">Idade (Animal)</label>
            <input type="text" asp-for="Animal.Age" class="form-control" placeholder="Idade do animal">
            @Html.ValidationMessageFor(x => x.Animal.Age)
        </div>
        <div class="form-group">
            <label for="name_veterinary">Veterinário</label>
            <input type="text" asp-for="Veterinary.Name" class="form-control" placeholder="Nome do veterinário">
            @Html.ValidationMessageFor(x => x.Veterinary.Name)
        </div>
        <br />
        <div class="form-group col-md-6">
          <button class="btn btn-success" role="button" type="submit"><i class="glyphicon glyphicon-ok"></i> Salvar</button>
          <a class="btn btn-danger" asp-action="Index" asp-controller="Treatment" role="button"><i class="glyphicon glyphicon-remove"></i> Cancelar</a>
        </div>
      </form>

src/Api/Views/Veterinary/Create.cshtml
@model Domain.Entities.Veterinary
@{
    ViewData["Title"] = "Cadastro de veterinário";
}

<div>
  <h2 class="display-4">Cadastro de veterinário</h2>
</div>
<br />

<form class="col-md-6" asp-controller="Veterinary" asp-action="Create" method="post">
    <div class="form-group mb-2">
      <label for="name">Nome</label>
      <input type="text" asp-for="Name" class="form-control" placeholder="Nome do veterinário">
      @Html.ValidationMessageFor(x => x.Name)
    </div>

    <br />
    <div class="form-group col-md-6 mb-2">
      <button class="btn btn-success" role="button" type="submit"><i class="glyphicon glyphicon-ok"></i> Salvar</button>
      <a class="btn btn-danger" asp-action="Index" asp-controller="Veterinary" role="button"><i class="glyphicon glyphicon-remove"></i> Cancelar</a>
    </div>
</form>

src/Api/Views/Veterinary/Delete.cshtml
@{
    ViewData["Title"] = "Excluindo veterinário";
}

<div class="text-center">
    <h3>Tem certeza que deseja excluir o veterinário <b>(@Model.Name)?</b></h3>
<br />

    <div class="btn-group" role="group">
            <a role="button" class="btn btn-success me-2" asp-action="ConfirmDelete" asp-controller="Veterinary" asp-route-id="@Model.Id"><i class="glyphicon glyphicon-ok-circle"></i> Sim</a>
            <a role="button" class="btn btn-danger me-2" asp-action="Index" asp-controller="Veterinary"><i class="glyphicon glyphicon-remove-circle"></i> Não</a>
    </div>
</div>

src/Api/Views/Veterinary/Index.cshtml
@model List<Domain.Entities.Veterinary>
@{
    ViewData["Title"] = "Veterinário";
}

<div className="main">
  <h2>Todos Veterinários</h2>
  <br />

<div class="">
    <a class="btn btn-primary" asp-controller="Veterinary" asp-action="Create"><i class="glyphicon glyphicon-plus"></i> Novo Veterinário</a>
</div>

<br />

  <table class="table table-borderless table-light" id="table">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Nome</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any())
              {
                  foreach (var veterinary in Model)
                  {
                      <tr>
                        <td>@Html.DisplayFor(modelItem => veterinary.Id)</td>
                        <td>@Html.DisplayFor(modelItem => veterinary.Name)</td>
                        <td>
                            <div class="btn-group" role="group">
                              <a role="button" class="btn btn-primary" asp-route-id="@veterinary.Id" asp-controller="Veterinary" asp-action="Update"><i class="glyphicon glyphicon-pencil"></i> Editar</a>
                              <a role="button" class="btn btn-danger" asp-route-id="@veterinary.Id" asp-controller="Veterinary" asp-action="Delete"><i class="glyphicon glyphicon-trash"></i> Excluir</a>
                            </div>
                        </td>
                      </tr>
                  }
              }
          </tbody>
  </table>
</div>

src/Api/Views/Veterinary/Update.cshtml
@model Domain.Entities.Veterinary
@{
    ViewData["Title"] = "Editar";
}

<div>
  <h2 class="display-4">Editar</h2>
</div>
      <form asp-controller="Veterinary" asp-action="Update" method="post">
        <input type="hidden" asp-for="Id"></input>
        <div class="form-group">
            <label for="name">Nome</label>
            <input type="text" asp-for="Name" class="form-control" id="name">
        </div>
        <br/>
        <div class="form-group col-md-6">
          <button class="btn btn-success" role="button" type="submit"><i class="glyphicon glyphicon-ok"></i> Salvar</button>
          <a class="btn btn-danger" asp-action="Index" asp-controller="Veterinary" role="button"><i class="glyphicon glyphicon-remove"></i> Cancelar</a>
        </div>
      </form>